Update calculation-groups.md
MicrosoftDocs/bi-shared-docs pull request #36
Opened 2021-08-16 18:39 UTC by gmuenster

I tested out creating reports on top of a PBI dataset using live connection and Dynamic Format Strings are not applied to report-level measures created in that report. I think that would be good to know.

2021-08-16 18:40 UTC, PRMerger6 commented
@gmuenster : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-08-17 16:32 UTC, Minewiskan requested changes
Thanks for pointing this out. Verified with engineering. Could you make a minor change to the first clause to read the following? I'll then approve and merge.

When creating Power BI reports using LiveConnection, Dynamic format strings are not applied to report-level measures.

Thank you!
-Minewiskan

2021-08-17 18:41 UTC, PRMerger16 commented
@gmuenster : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-08-17 18:42 UTC, gmuenster commented
Sure, I did change the first clause as proposed.

2021-08-17 19:22 UTC, merged